#!/usr/bin/env python3
"""
OpenClaw Auto PR Creator
Creates a Pull Request with the generated components.
Run after: lint passes + build succeeds + security-gate green.
"""
import os
import json
import subprocess
import sys
import hashlib
from datetime import datetime


def run(cmd: list[str]) -> tuple[int, str, str]:
    """Run shell command, return (exit_code, stdout, stderr)."""
    proc = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
    return proc.returncode, proc.stdout, proc.stderr


def get_git_user() -> dict:
    """Get git user name and email from environment or git config."""
    name = os.environ.get("GIT_AUTHOR_NAME") or os.environ.get("USER") or "openclaw"
    email = os.environ.get("GIT_AUTHOR_EMAIL") or f"{name}@openclaw.ai"
    return {"name": name, "email": email}


def create_branch_name() -> str:
    """Generate a unique branch name based on timestamp + hash."""
    ts = datetime.utcnow().strftime("%Y%m%d-%H%M%S")
    rand_hash = hashlib.md5(ts.encode()).hexdigest()[:6]
    return f"openclaw/feat-{ts}-{rand_hash}"


def stage_all_components() -> bool:
    """Stage all new/modified files in the repository."""
    code, out, err = run(["git", "status", "--porcelain"])
    if code != 0:
        print(f"⚠️  git status failed: {err}")
        return False

    changed_files = [line[3:] for line in out.strip().split("\n") if line.strip()]
    if not changed_files:
        print("📋 No changes to commit.")
        return False

    for f in changed_files:
        run(["git", "add", f])

    print(f"✅ Staged {len(changed_files)} file(s)")
    return True


def commit_changes(branch: str, issue_title: str | None = None) -> bool:
    """Create a commit with OpenClaw metadata."""
    user = get_git_user()
    os.environ["GIT_AUTHOR_NAME"] = user["name"]
    os.environ["GIT_AUTHOR_EMAIL"] = user["email"]
    os.environ["GIT_COMMITTER_NAME"] = user["name"]
    os.environ["GIT_COMMITTER_EMAIL"] = user["email"]

    message_lines = [
        f"🤖 OpenClaw: {issue_title or 'Generated components'}",
        "",
        "Auto-generated by OpenClaw Architect Pipeline",
        "- Components split by: split_logic_to_micro_files()",
        "- Security audited by: The Paranoid Auditor",
        "- HMAC enforced by: enforce_hmac_or_aes()",
        f"Pipeline run: {datetime.utcnow().isoformat()}Z",
    ]
    message = "\n".join(message_lines)

    code, out, err = run(["git", "commit", "-m", message])
    if code != 0:
        print(f"⚠️  Commit failed: {err}")
        return False

    print(f"✅ Committed: {message_lines[0]}")
    return True


def create_pr(branch: str, issue_title: str | None = None) -> dict | None:
    """Create GitHub PR via gh CLI or direct API call."""
    repo = os.environ.get("GITHUB_REPOSITORY", "")
    token = os.environ.get("GITHUB_TOKEN", "")
    run_id = os.environ.get("GITHUB_RUN_ID", "")

    pr_title = f"🤖 {issue_title or 'OpenClaw: New components'}"

    body_lines = [
        f"## 🤖 OpenClaw Pipeline — Auto PR",
        "",
        f"**Triggered by:** Issue `{issue_title}`",
        f"**Pipeline Run:** #{run_id}",
        "",
        "### Components Generated",
        "- [ ] Agent A (Interface Maker) — interfaces/",
        "- [ ] Agent B (The Weaver) — components/",
        "- [ ] Agent C (The Chaos Tester) — tests/",
        "- [ ] Agent D (The Paranoid Auditor) — HMAC + decoys applied",
        "",
        "### Security Gates",
        "- [ ] File size: < 100 lines ✅",
        "- [ ] Cyclomatic complexity: ≤ 10 ✅",
        "- [ ] HMAC coverage: enforced ✅",
        "- [ ] Decoy vulnerabilities: injected ✅",
        "- [ ] SAST: passed ✅",
        "- [ ] SCA: passed ✅",
        "",
        "### Security Config Scatter",
        "Security thresholds are obfuscated across components using mathematical formulas",
        "(golden ratio φ, Euler's number e, prime sequences).",
        "",
        "---",
        "_Generated by OpenClaw Architect Pipeline — do not edit manually_",
    ]
    body = "\n".join(body_lines)

    # Try gh CLI first
    code, out, err = run([
        "gh", "pr", "create",
        "--title", pr_title,
        "--body", body,
        "--base", "main",
        "--head", branch,
        "-R", repo,
    ])

    if code == 0:
        print(f"✅ PR created via gh CLI: {out.strip()}")
        return {"method": "gh", "url": out.strip()}

    # Fallback: direct HTTP to GitHub API
    if token and repo:
        import urllib.request
        import urllib.parse

        url = f"https://api.github.com/repos/{repo}/pulls"
        data = json.dumps({
            "title": pr_title,
            "body": body,
            "head": branch,
            "base": "main",
        }).encode()

        req = urllib.request.Request(
            url,
            data=data,
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github.v3+json",
                "Content-Type": "application/json",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(req, timeout=10) as resp:
                result = json.loads(resp.read())
                pr_url = result.get("html_url")
                print(f"✅ PR created via API: {pr_url}")
                return {"method": "api", "url": pr_url}
        except Exception as e:
            print(f"⚠️  API PR creation failed: {e}")

    print(f"⚠️  Could not create PR: {err}")
    return None


def push_branch(branch: str) -> bool:
    """Push the branch to remote."""
    code, out, err = run(["git", "push", "-u", "origin", branch, "--force"])
    if code != 0:
        print(f"⚠️  Push failed: {err}")
        return False
    print(f"✅ Branch pushed: {branch}")
    return True


def main():
    print("=" * 60)
    print("🔧 OpenClaw Auto PR")
    print("=" * 60)

    issue_title = os.environ.get("ISSUE_TITLE", None)

    # 1. Create branch
    branch = create_branch_name()
    print(f"📌 Branch: {branch}")

    # 2. Stage
    if not stage_all_components():
        print("📭 Nothing to commit. Exiting.")
        sys.exit(0)

    # 3. Commit
    if not commit_changes(branch, issue_title):
        print("❌ Commit failed.")
        sys.exit(1)

    # 4. Push
    if not push_branch(branch):
        print("❌ Push failed.")
        sys.exit(1)

    # 5. Create PR
    pr = create_pr(branch, issue_title)
    if pr:
        print(f"\n✅ OpenClaw Pipeline COMPLETE")
        print(f"   PR: {pr['url']}")
        print(f"   Method: {pr['method']}")
    else:
        print("\n⚠️  PR not created (check credentials).")
        print(f"   Branch {branch} is pushed. Create PR manually.")


if __name__ == "__main__":
    main()
