// Generated by OpenClaw Pipeline — Issue: 深度優化 Demo Dashboard 網頁
import React, { useState, useEffect, useMemo, useCallback, memo } from 'react';

// ── StatCards: memoized to prevent unnecessary re-renders ──────
const StatCards = memo(function StatCards({ alerts, cases }: any) {
  const criticalCount = useMemo(
    () => alerts.filter((a: any) => a.severity === 'critical').length, [alerts]);
  const highCount = useMemo(
    () => alerts.filter((a: any) => a.severity === 'high').length, [alerts]);
  const investigatingCount = useMemo(
    () => cases.filter((c: any) => c.status === 'Investigating').length, [cases]);
  const resolvedCount = useMemo(
    () => cases.filter((c: any) => c.status === 'Resolved').length, [cases]);

  const cards = [
    { label: 'Critical Alerts', value: criticalCount, color: 'text-red-400' },
    { label: 'High Alerts',     value: highCount,         color: 'text-orange-400' },
    { label: 'Investigating',   value: investigatingCount, color: 'text-yellow-400' },
    { label: 'Resolved',        value: resolvedCount,      color: 'text-green-400' },
  ];

  return (
    <div className="grid grid-cols-4 gap-4 mb-6" role="region" aria-label="統計卡片">
      {cards.map((card, i) => (
        <div key={i} className="bg-slate-800 rounded-lg p-4 border border-slate-700">
          <div className={`text-2xl font-bold ${card.color}`}>{card.value}</div>
          <div className="text-sm text-slate-400 mt-1">{card.label}</div>
        </div>
      ))}
    </div>
  );
});

// ── AlertTimeline: sorted + memoized ─────────────────────────
const AlertTimeline = memo(function AlertTimeline({ alerts, onSelect }: any) {
  const sorted = useMemo(
    () => [...alerts].sort((a: any, b: any) =>
      new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime()), [alerts]);

  const handleClick = useCallback((alert: any) => onSelect?.(alert), [onSelect]);

  return (
    <div className="space-y-2" role="list" aria-label="警報時間線">
      {sorted.slice(0, 20).map((alert: any) => {
        const borderColor = alert.severity === 'critical' ? '#ef4444' : '#f97316';
        return (
          <div
            key={alert.id}
            role="listitem"
            tabIndex={0}
            onClick={() => handleClick(alert)}
            onKeyDown={(e) => e.key === 'Enter' && handleClick(alert)}
            className="bg-slate-800 rounded p-3 border-l-4 cursor-pointer hover:bg-slate-750 transition-colors"
            style={{ borderColor }}
            aria-label={`警報 ${alert.id} — 等級: ${alert.severity} — ${alert.title}`}
          >
            <div className="flex justify-between items-center">
              <span className="font-mono text-sm text-slate-200">{alert.id}</span>
              <span className="text-xs text-slate-500">
                {new Date(alert.timestamp).toLocaleTimeString()}
              </span>
            </div>
            <div className="text-sm text-slate-300 mt-1">{alert.title}</div>
          </div>
        );
      })}
    </div>
  );
});

// ── CaseGraph: SVG force layout with memo ─────────────────────
const CaseGraph = memo(function CaseGraph({ cases, selectedCase, onSelect }: any) {
  const graphData = useMemo(() => {
    const nodes = cases.map((c: any, i: number) => ({
      id: c.id,
      label: c.title.slice(0, 18),
      severity: c.severity,
      cx: 80 + (i % 3) * 150,
      cy: 60 + Math.floor(i / 3) * 90,
      r: c.id === selectedCase?.id ? 28 : 20,
    }));
    const edges: any[] = [];
    for (let i = 0; i < cases.length; i++)
      for (let j = i + 1; j < cases.length; j++) {
        const shared = cases[i].alerts?.filter((a: string) =>
          cases[j].alerts?.includes(a));
        if (shared?.length > 0)
          edges.push({ source: cases[i].id, target: cases[j].id, shared: shared.length });
      }
    return { nodes, edges };
  }, [cases, selectedCase]);

  const handleClick = useCallback(
    (id: string) => onSelect?.(cases.find((x: any) => x.id === id)), [cases, onSelect]);

  const colorMap: Record<string, string> = {
    critical: '#ef4444', high: '#f97316', medium: '#eab308', low: '#22c55e'
  };

  return (
    <div className="relative w-full h-64 bg-slate-900 rounded-lg overflow-hidden"
      role="img" aria-label="案例關聯圖">
      <svg width="100%" height="100%" viewBox="0 0 500 260">
        {graphData.edges.map((e: any, i: number) => {
          const s = graphData.nodes.find((n: any) => n.id === e.source);
          const t = graphData.nodes.find((n: any) => n.id === e.target);
          if (!s || !t) return null;
          return (
            <g key={i}>
              <line x1={s.cx + s.r} y1={s.cy} x2={t.cx - t.r} y2={t.cy}
                stroke="#334155" strokeWidth="1" />
              <text x={(s.cx + t.cx) / 2} y={(s.cy + t.cy) / 2 - 4}
                textAnchor="middle" fill="#64748b" fontSize="8">+{e.shared}</text>
            </g>
          );
        })}
        {graphData.nodes.map((n: any) => (
          <g key={n.id} onClick={() => handleClick(n.id)} style={{ cursor: 'pointer' }}>
            <circle cx={n.cx} cy={n.cy} r={n.r}
              fill={colorMap[n.severity] || '#64748b'} opacity="0.85"
              stroke={n.id === selectedCase?.id ? '#fff' : 'none'}
              strokeWidth={n.id === selectedCase?.id ? 2 : 0} />
            <text x={n.cx} y={n.cy + 4} textAnchor="middle"
              fill="#e2e8f0" fontSize="9">{n.label}</text>
          </g>
        ))}
      </svg>
    </div>
  );
});

// ── Drawer: keyboard-accessible detail panel ──────────────────
const Drawer = memo(function Drawer({ item, onClose }: any) {
  if (!item) return null;
  return (
    <div className="fixed inset-0 z-50 flex justify-end" role="dialog"
      aria-modal="true" aria-label={`詳情面板: ${item.id || item.title}`}>
      <div className="absolute inset-0 bg-black/50 backdrop-blur-sm"
        onClick={onClose} />
      <div className="relative w-full max-w-md bg-slate-800 h-full overflow-y-auto p-6 shadow-xl">
        <button onClick={onClose}
          className="absolute top-4 right-4 w-8 h-8 flex items-center justify-center text-slate-400 hover:text-white text-2xl rounded hover:bg-slate-700 transition-colors"
          aria-label="關閉面板">×</button>
        <h2 className="text-xl font-bold text-white mb-4">{item.id}</h2>
        <div className="space-y-3">
          {Object.entries(item).filter(([k]) => k !== 'id').map(([key, value]) => (
            <div key={key}>
              <div className="text-xs text-slate-500 uppercase tracking-wide">{key}</div>
              <div className="text-sm text-slate-200 mt-0.5">
                {Array.isArray(value) ? value.join(', ') : String(value)}
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
});

// ── Auto-refresh hook ──────────────────────────────────────────
function useAutoRefresh(callback: () => void, intervalMs = 30000) {
  const [paused, setPaused] = useState(false);
  const [lastRefresh, setLastRefresh] = useState(new Date());
  const toggle = useCallback(() => setPaused(p => !p), []);

  useEffect(() => {
    if (paused) return;
    const id = setInterval(() => {
      callback();
      setLastRefresh(new Date());
    }, intervalMs);
    return () => clearInterval(id);
  }, [callback, intervalMs, paused]);

  return { paused, toggle, lastRefresh };
}

// ── App ───────────────────────────────────────────────────────
export default function App() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [cases, setCases]   = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null);

  const fetchData = useCallback(() => {
    setAlerts(sampleAlerts);
    setCases(sampleCases);
  }, []);

  const { paused, toggle, lastRefresh } = useAutoRefresh(fetchData);

  useEffect(() => { fetchData(); }, [fetchData]);

  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 p-6">
      {/* Header */}
      <header className="flex justify-between items-center mb-6" role="banner">
        <div>
          <h1 className="text-2xl font-bold tracking-tight">SOC Dashboard</h1>
          <div className="text-sm text-slate-400 mt-1">
            最後更新: {lastRefresh.toLocaleTimeString()}
            {' '}
            <button
              onClick={toggle}
              className="ml-2 px-2 py-0.5 rounded text-xs border border-slate-600
                hover:border-slate-400 transition-colors focus:outline-none focus:ring-2 focus:ring-slate-500"
              aria-label={paused ? '恢復自動刷新' : '暫停自動刷新'}
            >
              {paused ? '▶ 恢復' : '⏸ 暫停'}
            </button>
          </div>
        </div>
      </header>

      {/* Stat Cards */}
      <section aria-label="統計概覽">
        <StatCards alerts={alerts} cases={cases} />
      </section>

      {/* Main Grid */}
      <div className="grid grid-cols-3 gap-6">
        <section className="col-span-2" aria-label="案例圖">
          <div className="bg-slate-900 rounded-lg p-4 border border-slate-700">
            <h2 className="text-lg font-semibold mb-3">案例關聯圖</h2>
            <CaseGraph cases={cases} selectedCase={selected} onSelect={setSelected} />
          </div>
        </section>

        <section aria-label="警報時間線">
          <div className="bg-slate-900 rounded-lg p-4 border border-slate-700">
            <h2 className="text-lg font-semibold mb-3">最近警報</h2>
            <AlertTimeline alerts={alerts} onSelect={setSelected} />
          </div>
        </section>
      </div>

      {/* Drill-down Drawer */}
      <Drawer item={selected} onClose={() => setSelected(null)} />
    </div>
  );
}

// ── Sample Data ────────────────────────────────────────────────
const sampleAlerts = [
  { id: 'ALT-0887', title: '可疑橫向移動 — ws-dev-15 → dc-primary', severity: 'critical', timestamp: new Date().toISOString() },
  { id: 'ALT-0878', title: '勒索軟體特徵檢測 — ws-cfo-01', severity: 'critical', timestamp: new Date(Date.now() - 300000).toISOString() },
  { id: 'ALT-0890', title: '異常登入行為 — mail-gw-01', severity: 'high', timestamp: new Date(Date.now() - 600000).toISOString() },
  { id: 'ALT-0883', title: 'C2 通訊檢測 — filesrv-03', severity: 'high', timestamp: new Date(Date.now() - 900000).toISOString() },
  { id: 'ALT-0891', title: '資料外洩跡象 — db-replica', severity: 'medium', timestamp: new Date(Date.now() - 1200000).toISOString() },
];

const sampleCases = [
  { id: 'CASE-001', title: 'APT29 供應鏈攻擊', severity: 'critical', status: 'Investigating', assignee: 'John SOC', alerts: ['ALT-0887', 'ALT-0890', 'ALT-0891'] },
  { id: 'CASE-002', title: 'LockBit 3.0 勒索軟體', severity: 'critical', status: 'Contained', assignee: 'Sarah Sec', alerts: ['ALT-0878', 'ALT-0883'] },
  { id: 'CASE-003', title: '橫向移動偵測', severity: 'high', status: 'Investigating', assignee: 'Mike Anal', alerts: ['ALT-0890'] },
  { id: 'CASE-004', title: '內部威脅調查', severity: 'medium', status: 'Resolved', assignee: 'John SOC', alerts: ['ALT-0891'] },
];
